//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void IDAC0_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define LED0_PIN                (4)
#define LED0_PORT               (gpioPortF)

#define LED1_PIN                (3)
#define LED1_PORT               (gpioPortF)

#define SHARPLCD_CS_PIN         (13)
#define SHARPLCD_CS_PORT        (gpioPortE)

#define SHARPLCD_DISP_PIN       (4)
#define SHARPLCD_DISP_PORT      (gpioPortD)

#define SHARPLCD_VCOM_PIN       (5)
#define SHARPLCD_VCOM_PORT      (gpioPortD)

#define USART0_CLK_PIN          (12)
#define USART0_CLK_PORT         (gpioPortE)

#define USART0_RX_PIN           (11)
#define USART0_RX_PORT          (gpioPortE)

#define USART0_TX_PIN           (10)
#define USART0_TX_PORT          (gpioPortE)

#define USART1_CLK_PIN          (7)
#define USART1_CLK_PORT         (gpioPortB)

#define USART1_RX_PIN           (1)
#define USART1_RX_PORT          (gpioPortC)

#define USART1_TX_PIN           (0)
#define USART1_TX_PORT          (gpioPortC)

// [User-defined pin name abstraction]$

#endif

